# Generated by Django 4.0.6 on 2022-07-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("url_shortener_api", "0003_alter_unshortenlink_original_link_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UnshortenLink",
            new_name="UnshortenerLink",
        ),
    ]
